#
# Ansible to provision OpenVPN on remote host
#
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  pre_tasks:
    - name: Wait up to 600 seconds for EC2 bootstrap
      wait_for_connection:
        timeout: 600
    - name: Gather facts
      setup:
  roles:
    - kykl191.openvpn
  vars:
    openvpn_client_register_dns: false  # Only Windows client supports this
    clients: [guest]
  tasks:
    # Download the remote files which will be used in any
    # client-side, i.e. for tunnelblick
    - name: Grab a list of VPN configuration files
      find: paths="/etc/openvpn/" recurse=no patterns="*.ovpn"
      register: files_to_grab
    - name: Download VPN configuration tarball from the server
      fetch:
        src: "{{ item.path }}"
        dest: ../keys
        flat: yes
      with_items: "{{ files_to_grab.files }}"
